# Generated by Django 2.2.10 on 2024-05-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20210410_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '前台用户', 'verbose_name_plural': '前台用户'},
        ),
    ]
